name: Auto Deploy after push

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: git checkout
        uses: actions/checkout@v3

      - name: npm install
        run: npm install

      - name: npm build
        run: npm run build
        env:
          CI: false

      - name: deploy s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 sync --delete --region ap-northeast-2 ./dist s3://picpic-bucket
